#ifndef _out_arm_plat_sprd_core_include_generated_conf_h_
#define _out_arm_plat_sprd_core_include_generated_conf_h_
#define CFG_ARM32_core 1 /* 'y' */
#define CFG_ARM32_user_ta 1 /* 'y' */
#define CFG_CRYPTO 1 /* 'y' */
#define CFG_CRYPTO_AES 1 /* 'y' */
#define CFG_CRYPTO_CBC 1 /* 'y' */
#define CFG_CRYPTO_CBC_MAC 1 /* 'y' */
#define CFG_CRYPTO_CCM 1 /* 'y' */
#define CFG_CRYPTO_CMAC 1 /* 'y' */
#define CFG_CRYPTO_CONCAT_KDF 1 /* 'y' */
#define CFG_CRYPTO_CTR 1 /* 'y' */
#define CFG_CRYPTO_CTS 1 /* 'y' */
#define CFG_CRYPTO_DES 1 /* 'y' */
#define CFG_CRYPTO_DH 1 /* 'y' */
#define CFG_CRYPTO_DSA 1 /* 'y' */
#define CFG_CRYPTO_ECB 1 /* 'y' */
#define CFG_CRYPTO_ECC 1 /* 'y' */
#define CFG_CRYPTO_GCM 1 /* 'y' */
#define CFG_CRYPTO_HKDF 1 /* 'y' */
#define CFG_CRYPTO_HMAC 1 /* 'y' */
#define CFG_CRYPTO_MD5 1 /* 'y' */
#define CFG_CRYPTO_PBKDF2 1 /* 'y' */
#define CFG_CRYPTO_RSA 1 /* 'y' */
#define CFG_CRYPTO_SHA1 1 /* 'y' */
#define CFG_CRYPTO_SHA224 1 /* 'y' */
#define CFG_CRYPTO_SHA256 1 /* 'y' */
#define CFG_CRYPTO_SHA384 1 /* 'y' */
#define CFG_CRYPTO_SHA512 1 /* 'y' */
#define CFG_CRYPTO_XTS 1 /* 'y' */
#define CFG_ENC_FS 1 /* 'y' */
#define CFG_GENERIC_BOOT 1 /* 'y' */
#define CFG_GIC 1 /* 'y' */
#define CFG_HWSUPP_MEM_PERM_PXN 1 /* 'y' */
#define CFG_KERN_LINKER_ARCH arm /* 'arm' */
#define CFG_KERN_LINKER_FORMAT elf32-littlearm /* 'elf32-littlearm' */
#define CFG_MMU_V7_TTB 1 /* 'y' */
#define CFG_NUM_THREADS 2 /* '2' */
#define CFG_PL011 1 /* 'y' */
#define CFG_PM_STUBS 1 /* 'y' */
#define CFG_SECURE_TIME_SOURCE_CNTPCT 1 /* 'y' */
#define CFG_TEE_API_VERSION GPD-1.1-dev /* 'GPD-1.1-dev' */
#define CFG_TEE_CORE_DEBUG 0 /* '0' */
#define CFG_TEE_CORE_EMBED_INTERNAL_TESTS 1 /* 'y' */
#define CFG_TEE_CORE_LOG_LEVEL 4 /* '4' */
#define CFG_TEE_CORE_TA_TRACE 1 /* 'y' */
#define CFG_TEE_CORE_USER_MEM_DEBUG 1 /* '1' */
#define CFG_TEE_FS_KEY_MANAGER_TEST 1 /* 'y' */
#define CFG_TEE_FW_IMPL_VERSION FW_IMPL_UNDEF /* 'FW_IMPL_UNDEF' */
#define CFG_TEE_FW_MANUFACTURER FW_MAN_UNDEF /* 'FW_MAN_UNDEF' */
#define CFG_TEE_IMPL_DESCR OPTEE /* 'OPTEE' */
#define CFG_TEE_IMPL_VERSION 1.0.1-1-g1fb7624 /* '1.0.1-1-g1fb7624' */
#define CFG_TEE_MANUFACTURER LINARO /* 'LINARO' */
#define CFG_TEE_TA_LOG_LEVEL 1 /* '1' */
#define CFG_WITH_ARM_TRUSTED_FW 1 /* 'y' */
#define CFG_WITH_SOFTWARE_PRNG 1 /* 'y' */
#define CFG_WITH_STACK_CANARIES 1 /* 'y' */
#define _CFG_CRYPTO_WITH_ACIPHER 1 /* 'y' */
#define _CFG_CRYPTO_WITH_ASN1 1 /* 'y' */
#define _CFG_CRYPTO_WITH_AUTHENC 1 /* 'y' */
#define _CFG_CRYPTO_WITH_CBC 1 /* 'y' */
#define _CFG_CRYPTO_WITH_CIPHER 1 /* 'y' */
#define _CFG_CRYPTO_WITH_FORTUNA_PRNG 1 /* 'y' */
#define _CFG_CRYPTO_WITH_HASH 1 /* 'y' */
#define _CFG_CRYPTO_WITH_MAC 1 /* 'y' */
#endif
