
package com.android.sprd.telephony;

public interface RIConstants {

    int MISSING_RESOURCE = 16;
    int NO_SUCH_ELEMENT = 17;

    String RADIOINTERACTOR_SERVER = "irit";

    int RI_REQUEST_RADIOINTERACTOR = -1;
    int RI_REQUEST_OEM_HOOK_STRINGS = 60;
    int RI_REQUEST_SIM_TRANSMIT_APDU_BASIC = 114;
    int RI_REQUEST_SIM_OPEN_CHANNEL = 115;
    int RI_REQUEST_SIM_CLOSE_CHANNEL = 116;
    int RI_REQUEST_SIM_TRANSMIT_APDU_CHANNEL = 117;
    int RI_REQUEST_SHUTDOWN =129;

    int RI_RESPONSE_ACKNOWLEDGEMENT = 800; // TBD

    int RI_UNSOL_RADIOINTERACTOR_EMBMS = -1;

    int RI_REQUEST_BASE =4000;
    int RI_REQUEST_VIDEOPHONE_DIAL = RI_REQUEST_BASE +1;
    int RI_REQUEST_VIDEOPHONE_CODEC = RI_REQUEST_BASE +2;
    int RI_REQUEST_VIDEOPHONE_FALLBACK = RI_REQUEST_BASE +3;
    int RI_REQUEST_VIDEOPHONE_STRING = RI_REQUEST_BASE +4;
    int RI_REQUEST_VIDEOPHONE_LOCAL_MEDIA = RI_REQUEST_BASE+5;
    int RI_REQUEST_VIDEOPHONE_CONTROL_IFRAME = RI_REQUEST_BASE+6;
    int RI_REQUEST_SWITCH_MULTI_CALL = RI_REQUEST_BASE +7;
    int RI_REQUEST_DC_TRAFFIC_CLASS = RI_REQUEST_BASE+8;
    int RI_REQUEST_ENABLE_LTE = RI_REQUEST_BASE + 9;
    int RI_REQUEST_ATTACH_DATACONN = RI_REQUEST_BASE + 10;
    int RI_REQUEST_ABORT_SEARCH_NETWORK = RI_REQUEST_BASE +11;
    int RI_REQUEST_DC_FORCE_DETACH = RI_REQUEST_BASE +12;
    int RI_REQUEST_GET_HD_VOICE_STATE = RI_REQUEST_BASE +13;
    int RI_REQUEST_SIM_POWER = RI_REQUEST_BASE +14;
    int RI_REQUEST_ENABLE_RAU_NOTIFY = RI_REQUEST_BASE+15;
    int RI_REQUEST_ENABLE_COLP = RI_REQUEST_BASE+16;
    int RI_REQUEST_GET_DEFAULT_NAN = RI_REQUEST_BASE +17;
    int RI_REQUEST_SIM_GET_ATR = RI_REQUEST_BASE +18;
    int RI_REQUEST_SIM_OPEN_CHANNEL_WITH_P2 = RI_REQUEST_BASE +19;
    int RI_REQUEST_GET_SIM_CAPACITY = RI_REQUEST_BASE +20;
    int RI_REQUEST_STORE_SMS_TO_SIM = RI_REQUEST_BASE +21;
    int RI_REQUEST_QUERY_SMS_STORAGE_MODE = RI_REQUEST_BASE +22;
    int RI_REQUEST_GET_SIMLOCK_REMAIN_TIMES = RI_REQUEST_BASE + 23;
    int RI_REQUEST_SET_FACILITY_LOCK_FOR_USER = RI_REQUEST_BASE + 24;
    int RI_REQUEST_GET_SIMLOCK_STATUS = RI_REQUEST_BASE + 25;
    int RI_REQUEST_GET_SIMLOCK_DUMMYS = RI_REQUEST_BASE + 26;
    int RI_REQUEST_GET_SIMLOCK_WHITE_LIST = RI_REQUEST_BASE + 27;
    int RI_REQUEST_UPDATE_REAL_ECCLIST  = RI_REQUEST_BASE + 28;
    int RI_REQUEST_GET_BAND_INFO = RI_REQUEST_BASE + 29;
    int RI_REQUEST_SET_BAND_INFO_MODE = RI_REQUEST_BASE + 30;
    int RI_REQUEST_SET_SINGLE_PDN = RI_REQUEST_BASE + 31;
    int RI_REQUEST_SET_SPECIAL_RATCAP = RI_REQUEST_BASE + 32;
    int RI_REQUEST_QUERY_COLP = RI_REQUEST_BASE + 33;
    int RI_REQUEST_QUERY_COLR = RI_REQUEST_BASE + 34;
    int RI_REQUEST_MMI_ENTER_SIM = RI_REQUEST_BASE + 35;

    int RI_UNSOL_RESPONSE_BASE = 5000;
    int RI_UNSOL_VIDEOPHONE_CODEC = RI_UNSOL_RESPONSE_BASE+0;
    int RI_UNSOL_VIDEOPHONE_DSCI = RI_UNSOL_RESPONSE_BASE+1;
    int RI_UNSOL_VIDEOPHONE_STRING = RI_UNSOL_RESPONSE_BASE+2;
    int RI_UNSOL_VIDEOPHONE_REMOTE_MEDIA = RI_UNSOL_RESPONSE_BASE+3;
    int RI_UNSOL_VIDEOPHONE_MM_RING = RI_UNSOL_RESPONSE_BASE+4;
    int RI_UNSOL_VIDEOPHONE_RELEASING = RI_UNSOL_RESPONSE_BASE+5;
    int RI_UNSOL_VIDEOPHONE_RECORD_VIDEO = RI_UNSOL_RESPONSE_BASE+6;
    int RI_UNSOL_VIDEOPHONE_MEDIA_START = RI_UNSOL_RESPONSE_BASE+7;
    int RI_UNSOL_ECC_NETWORKLIST_CHANGED = RI_UNSOL_RESPONSE_BASE+8;
    int RI_UNSOL_RAU_NOTIFY = RI_UNSOL_RESPONSE_BASE+9;
    int RI_UNSOL_CLEAR_CODE_FALLBACK = RI_UNSOL_RESPONSE_BASE+10;
    int RI_UNSOL_RI_CONNECTED = RI_UNSOL_RESPONSE_BASE+11;
    int RI_UNSOL_SIMLOCK_STATUS_CHANGED = RI_UNSOL_RESPONSE_BASE+12;
    int RI_UNSOL_BAND_INFO = RI_UNSOL_RESPONSE_BASE+14;
}
