/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "rrlp-components.asn"
 * 	`asn1c -gen-PER -fnative-types`
 */

#ifndef	_AdditionalAssistanceData_H_
#define	_AdditionalAssistanceData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GPSAssistanceData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionContainer;

/* AdditionalAssistanceData */
typedef struct AdditionalAssistanceData {
	GPSAssistanceData_t	*gpsAssistanceData	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdditionalAssistanceData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalAssistanceData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionContainer.h"

#endif	/* _AdditionalAssistanceData_H_ */
#include <asn_internal.h>
