ASN_MODULE_SOURCES=	\
	ULP-PDU.c	\
	UlpMessage.c	\
	SUPLINIT.c	\
	Notification.c	\
	NotificationType.c	\
	EncodingType.c	\
	FormatIndicator.c	\
	SLPMode.c	\
	MAC.c	\
	KeyIdentity.c	\
	SUPLSTART.c	\
	SETCapabilities.c	\
	PosTechnology.c	\
	PrefMethod.c	\
	PosProtocol.c	\
	SUPLRESPONSE.c	\
	SETAuthKey.c	\
	KeyIdentity4.c	\
	SUPLPOSINIT.c	\
	RequestedAssistData.c	\
	NavigationModel-1.c	\
	SatelliteInfo.c	\
	SatelliteInfoElement.c	\
	SUPLPOS.c	\
	PosPayLoad.c	\
	SUPLEND.c	\
	SUPLAUTHREQ.c	\
	SETNonce.c	\
	KeyIdentity2.c	\
	SUPLAUTHRESP.c	\
	SPCAuthKey.c	\
	KeyIdentity3.c	\
	Version.c	\
	SessionID.c	\
	SetSessionID.c	\
	SETId.c	\
	SlpSessionID.c	\
	IPAddress.c	\
	SLPAddress.c	\
	FQDN.c	\
	Ver.c	\
	LocationId.c	\
	Status.c	\
	CellInfo.c	\
	Position.c	\
	PositionEstimate.c	\
	AltitudeInfo.c	\
	CdmaCellInformation.c	\
	GsmCellInformation.c	\
	WcdmaCellInformation.c	\
	FrequencyInfo.c	\
	FrequencyInfoFDD.c	\
	FrequencyInfoTDD.c	\
	UARFCN.c	\
	NMR.c	\
	NMRelement.c	\
	MeasuredResultsList.c	\
	MeasuredResults.c	\
	CellMeasuredResultsList.c	\
	UTRA-CarrierRSSI.c	\
	CellMeasuredResults.c	\
	CellParametersID.c	\
	TGSN.c	\
	PrimaryCCPCH-RSCP.c	\
	TimeslotISCP.c	\
	TimeslotISCP-List.c	\
	PrimaryCPICH-Info.c	\
	CPICH-Ec-N0.c	\
	CPICH-RSCP.c	\
	Pathloss.c	\
	StatusCode.c	\
	QoP.c	\
	Velocity.c	\
	Horvel.c	\
	Horandvervel.c	\
	Horveluncert.c	\
	Horandveruncert.c	\
	PosMethod.c	\
	PDU.c	\
	RRLP-Component.c	\
	MsrPosition-Req.c	\
	MsrPosition-Rsp.c	\
	AssistanceData.c	\
	ProtocolError.c	\
	PositionInstruct.c	\
	MethodType.c	\
	AccuracyOpt.c	\
	Accuracy.c	\
	PositionMethod.c	\
	MeasureResponseTime.c	\
	UseMultipleSets.c	\
	EnvironmentCharacter.c	\
	ReferenceAssistData.c	\
	BTSPosition.c	\
	BCCHCarrier.c	\
	BSIC.c	\
	TimeSlotScheme.c	\
	ModuloTimeSlot.c	\
	MsrAssistData.c	\
	SeqOfMsrAssistBTS.c	\
	MsrAssistBTS.c	\
	MultiFrameOffset.c	\
	RoughRTD.c	\
	SystemInfoAssistData.c	\
	SeqOfSystemInfoAssistBTS.c	\
	SystemInfoAssistBTS.c	\
	AssistBTSData.c	\
	CalcAssistanceBTS.c	\
	ReferenceWGS84.c	\
	FineRTD.c	\
	RelDistance.c	\
	RelativeAlt.c	\
	MultipleSets.c	\
	ReferenceRelation.c	\
	ReferenceIdentity.c	\
	SeqOfReferenceIdentityType.c	\
	ReferenceIdentityType.c	\
	BSICAndCarrier.c	\
	RequestIndex.c	\
	SystemInfoIndex.c	\
	CellIDAndLAC.c	\
	CellID.c	\
	LAC.c	\
	OTD-MeasureInfo.c	\
	SeqOfOTD-MsrElementRest.c	\
	OTD-MsrElementFirst.c	\
	SeqOfOTD-FirstSetMsrs.c	\
	OTD-MsrElementRest.c	\
	SeqOfOTD-MsrsOfOtherSets.c	\
	TOA-MeasurementsOfRef.c	\
	RefQuality.c	\
	NumOfMeasurements.c	\
	StdResolution.c	\
	OTD-FirstSetMsrs.c	\
	OTD-MsrsOfOtherSets.c	\
	OTD-Measurement.c	\
	OTD-MeasurementWithID.c	\
	EOTDQuality.c	\
	NeighborIdentity.c	\
	MultiFrameCarrier.c	\
	OTDValue.c	\
	LocationInfo.c	\
	FixType.c	\
	GPS-MeasureInfo.c	\
	SeqOfGPS-MsrSetElement.c	\
	GPS-MsrSetElement.c	\
	GPSTOW24b.c	\
	SeqOfGPS-MsrElement.c	\
	GPS-MsrElement.c	\
	MpathIndic.c	\
	LocationError.c	\
	LocErrorReason.c	\
	AdditionalAssistanceData.c	\
	GPSAssistanceData.c	\
	ErrorCodes.c	\
	GPS-AssistData.c	\
	MoreAssDataToBeSent.c	\
	ControlHeader.c	\
	ReferenceTime.c	\
	GPSTime.c	\
	GPSTOW23b.c	\
	GPSWeek.c	\
	GPSTOWAssist.c	\
	GPSTOWAssistElement.c	\
	TLMWord.c	\
	AntiSpoofFlag.c	\
	AlertFlag.c	\
	TLMReservedBits.c	\
	GSMTime.c	\
	FrameNumber.c	\
	TimeSlot.c	\
	BitNumber.c	\
	RefLocation.c	\
	DGPSCorrections.c	\
	SeqOfSatElement.c	\
	SatElement.c	\
	SatelliteID.c	\
	NavigationModel.c	\
	SeqOfNavModelElement.c	\
	NavModelElement.c	\
	SatStatus.c	\
	UncompressedEphemeris.c	\
	EphemerisSubframe1Reserved.c	\
	IonosphericModel.c	\
	UTCModel.c	\
	Almanac.c	\
	SeqOfAlmanacElement.c	\
	AlmanacElement.c	\
	AcquisAssist.c	\
	SeqOfAcquisElement.c	\
	TimeRelation.c	\
	AcquisElement.c	\
	AddionalDopplerFields.c	\
	AddionalAngleFields.c	\
	SeqOf-BadSatelliteSet.c	\
	Rel98-MsrPosition-Req-Extension.c	\
	Rel98-AssistanceData-Extension.c	\
	Rel98-Ext-ExpOTD.c	\
	MsrAssistData-R98-ExpOTD.c	\
	SeqOfMsrAssistBTS-R98-ExpOTD.c	\
	MsrAssistBTS-R98-ExpOTD.c	\
	SystemInfoAssistData-R98-ExpOTD.c	\
	SeqOfSystemInfoAssistBTS-R98-ExpOTD.c	\
	SystemInfoAssistBTS-R98-ExpOTD.c	\
	AssistBTSData-R98-ExpOTD.c	\
	ExpectedOTD.c	\
	ExpOTDUncertainty.c	\
	GPSReferenceTimeUncertainty.c	\
	GPSTimeAssistanceMeasurements.c	\
	Rel-98-MsrPosition-Rsp-Extension.c	\
	OTD-MeasureInfo-R98-Ext.c	\
	OTD-MsrElementFirst-R98-Ext.c	\
	SeqOfOTD-FirstSetMsrs-R98-Ext.c	\
	Rel-5-MsrPosition-Rsp-Extension.c	\
	Extended-reference.c	\
	OTD-MeasureInfo-5-Ext.c	\
	UlPseudoSegInd.c	\
	Rel5-MsrPosition-Req-Extension.c	\
	Rel5-AssistanceData-Extension.c	\
	Rel-5-ProtocolError-Extension.c	\
	ExtensionContainer.c	\
	SLR-ArgExtensionContainer.c	\
	PrivateExtensionList.c	\
	PrivateExtension.c	\
	PCS-Extensions.c	\
	SLR-Arg-PCS-Extensions.c	\
	Ext-GeographicalInformation.c

ASN_MODULE_HEADERS=	\
	ULP-PDU.h	\
	UlpMessage.h	\
	SUPLINIT.h	\
	Notification.h	\
	NotificationType.h	\
	EncodingType.h	\
	FormatIndicator.h	\
	SLPMode.h	\
	MAC.h	\
	KeyIdentity.h	\
	SUPLSTART.h	\
	SETCapabilities.h	\
	PosTechnology.h	\
	PrefMethod.h	\
	PosProtocol.h	\
	SUPLRESPONSE.h	\
	SETAuthKey.h	\
	KeyIdentity4.h	\
	SUPLPOSINIT.h	\
	RequestedAssistData.h	\
	NavigationModel-1.h	\
	SatelliteInfo.h	\
	SatelliteInfoElement.h	\
	SUPLPOS.h	\
	PosPayLoad.h	\
	SUPLEND.h	\
	SUPLAUTHREQ.h	\
	SETNonce.h	\
	KeyIdentity2.h	\
	SUPLAUTHRESP.h	\
	SPCAuthKey.h	\
	KeyIdentity3.h	\
	Version.h	\
	SessionID.h	\
	SetSessionID.h	\
	SETId.h	\
	SlpSessionID.h	\
	IPAddress.h	\
	SLPAddress.h	\
	FQDN.h	\
	Ver.h	\
	LocationId.h	\
	Status.h	\
	CellInfo.h	\
	Position.h	\
	PositionEstimate.h	\
	AltitudeInfo.h	\
	CdmaCellInformation.h	\
	GsmCellInformation.h	\
	WcdmaCellInformation.h	\
	FrequencyInfo.h	\
	FrequencyInfoFDD.h	\
	FrequencyInfoTDD.h	\
	UARFCN.h	\
	NMR.h	\
	NMRelement.h	\
	MeasuredResultsList.h	\
	MeasuredResults.h	\
	CellMeasuredResultsList.h	\
	UTRA-CarrierRSSI.h	\
	CellMeasuredResults.h	\
	CellParametersID.h	\
	TGSN.h	\
	PrimaryCCPCH-RSCP.h	\
	TimeslotISCP.h	\
	TimeslotISCP-List.h	\
	PrimaryCPICH-Info.h	\
	CPICH-Ec-N0.h	\
	CPICH-RSCP.h	\
	Pathloss.h	\
	StatusCode.h	\
	QoP.h	\
	Velocity.h	\
	Horvel.h	\
	Horandvervel.h	\
	Horveluncert.h	\
	Horandveruncert.h	\
	PosMethod.h	\
	PDU.h	\
	RRLP-Component.h	\
	MsrPosition-Req.h	\
	MsrPosition-Rsp.h	\
	AssistanceData.h	\
	ProtocolError.h	\
	PositionInstruct.h	\
	MethodType.h	\
	AccuracyOpt.h	\
	Accuracy.h	\
	PositionMethod.h	\
	MeasureResponseTime.h	\
	UseMultipleSets.h	\
	EnvironmentCharacter.h	\
	ReferenceAssistData.h	\
	BTSPosition.h	\
	BCCHCarrier.h	\
	BSIC.h	\
	TimeSlotScheme.h	\
	ModuloTimeSlot.h	\
	MsrAssistData.h	\
	SeqOfMsrAssistBTS.h	\
	MsrAssistBTS.h	\
	MultiFrameOffset.h	\
	RoughRTD.h	\
	SystemInfoAssistData.h	\
	SeqOfSystemInfoAssistBTS.h	\
	SystemInfoAssistBTS.h	\
	AssistBTSData.h	\
	CalcAssistanceBTS.h	\
	ReferenceWGS84.h	\
	FineRTD.h	\
	RelDistance.h	\
	RelativeAlt.h	\
	MultipleSets.h	\
	ReferenceRelation.h	\
	ReferenceIdentity.h	\
	SeqOfReferenceIdentityType.h	\
	ReferenceIdentityType.h	\
	BSICAndCarrier.h	\
	RequestIndex.h	\
	SystemInfoIndex.h	\
	CellIDAndLAC.h	\
	CellID.h	\
	LAC.h	\
	OTD-MeasureInfo.h	\
	SeqOfOTD-MsrElementRest.h	\
	OTD-MsrElementFirst.h	\
	SeqOfOTD-FirstSetMsrs.h	\
	OTD-MsrElementRest.h	\
	SeqOfOTD-MsrsOfOtherSets.h	\
	TOA-MeasurementsOfRef.h	\
	RefQuality.h	\
	NumOfMeasurements.h	\
	StdResolution.h	\
	OTD-FirstSetMsrs.h	\
	OTD-MsrsOfOtherSets.h	\
	OTD-Measurement.h	\
	OTD-MeasurementWithID.h	\
	EOTDQuality.h	\
	NeighborIdentity.h	\
	MultiFrameCarrier.h	\
	OTDValue.h	\
	LocationInfo.h	\
	FixType.h	\
	GPS-MeasureInfo.h	\
	SeqOfGPS-MsrSetElement.h	\
	GPS-MsrSetElement.h	\
	GPSTOW24b.h	\
	SeqOfGPS-MsrElement.h	\
	GPS-MsrElement.h	\
	MpathIndic.h	\
	LocationError.h	\
	LocErrorReason.h	\
	AdditionalAssistanceData.h	\
	GPSAssistanceData.h	\
	ErrorCodes.h	\
	GPS-AssistData.h	\
	MoreAssDataToBeSent.h	\
	ControlHeader.h	\
	ReferenceTime.h	\
	GPSTime.h	\
	GPSTOW23b.h	\
	GPSWeek.h	\
	GPSTOWAssist.h	\
	GPSTOWAssistElement.h	\
	TLMWord.h	\
	AntiSpoofFlag.h	\
	AlertFlag.h	\
	TLMReservedBits.h	\
	GSMTime.h	\
	FrameNumber.h	\
	TimeSlot.h	\
	BitNumber.h	\
	RefLocation.h	\
	DGPSCorrections.h	\
	SeqOfSatElement.h	\
	SatElement.h	\
	SatelliteID.h	\
	NavigationModel.h	\
	SeqOfNavModelElement.h	\
	NavModelElement.h	\
	SatStatus.h	\
	UncompressedEphemeris.h	\
	EphemerisSubframe1Reserved.h	\
	IonosphericModel.h	\
	UTCModel.h	\
	Almanac.h	\
	SeqOfAlmanacElement.h	\
	AlmanacElement.h	\
	AcquisAssist.h	\
	SeqOfAcquisElement.h	\
	TimeRelation.h	\
	AcquisElement.h	\
	AddionalDopplerFields.h	\
	AddionalAngleFields.h	\
	SeqOf-BadSatelliteSet.h	\
	Rel98-MsrPosition-Req-Extension.h	\
	Rel98-AssistanceData-Extension.h	\
	Rel98-Ext-ExpOTD.h	\
	MsrAssistData-R98-ExpOTD.h	\
	SeqOfMsrAssistBTS-R98-ExpOTD.h	\
	MsrAssistBTS-R98-ExpOTD.h	\
	SystemInfoAssistData-R98-ExpOTD.h	\
	SeqOfSystemInfoAssistBTS-R98-ExpOTD.h	\
	SystemInfoAssistBTS-R98-ExpOTD.h	\
	AssistBTSData-R98-ExpOTD.h	\
	ExpectedOTD.h	\
	ExpOTDUncertainty.h	\
	GPSReferenceTimeUncertainty.h	\
	GPSTimeAssistanceMeasurements.h	\
	Rel-98-MsrPosition-Rsp-Extension.h	\
	OTD-MeasureInfo-R98-Ext.h	\
	OTD-MsrElementFirst-R98-Ext.h	\
	SeqOfOTD-FirstSetMsrs-R98-Ext.h	\
	Rel-5-MsrPosition-Rsp-Extension.h	\
	Extended-reference.h	\
	OTD-MeasureInfo-5-Ext.h	\
	UlPseudoSegInd.h	\
	Rel5-MsrPosition-Req-Extension.h	\
	Rel5-AssistanceData-Extension.h	\
	Rel-5-ProtocolError-Extension.h	\
	ExtensionContainer.h	\
	SLR-ArgExtensionContainer.h	\
	PrivateExtensionList.h	\
	PrivateExtension.h	\
	PCS-Extensions.h	\
	SLR-Arg-PCS-Extensions.h	\
	Ext-GeographicalInformation.h

ASN_MODULE_HEADERS+=ANY.h
ASN_MODULE_SOURCES+=ANY.c
ASN_MODULE_HEADERS+=BOOLEAN.h
ASN_MODULE_SOURCES+=BOOLEAN.c
ASN_MODULE_HEADERS+=INTEGER.h
ASN_MODULE_HEADERS+=NativeEnumerated.h
ASN_MODULE_HEADERS+=GeneralizedTime.h
ASN_MODULE_SOURCES+=GeneralizedTime.c
ASN_MODULE_HEADERS+=IA5String.h
ASN_MODULE_SOURCES+=IA5String.c
ASN_MODULE_SOURCES+=INTEGER.c
ASN_MODULE_HEADERS+=NULL.h
ASN_MODULE_SOURCES+=NULL.c
ASN_MODULE_SOURCES+=NativeEnumerated.c
ASN_MODULE_HEADERS+=NativeInteger.h
ASN_MODULE_SOURCES+=NativeInteger.c
ASN_MODULE_HEADERS+=OBJECT_IDENTIFIER.h
ASN_MODULE_SOURCES+=OBJECT_IDENTIFIER.c
ASN_MODULE_HEADERS+=UTCTime.h
ASN_MODULE_SOURCES+=UTCTime.c
ASN_MODULE_HEADERS+=VisibleString.h
ASN_MODULE_SOURCES+=VisibleString.c
ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=asn_SET_OF.h
ASN_MODULE_SOURCES+=asn_SET_OF.c
ASN_MODULE_HEADERS+=constr_CHOICE.h
ASN_MODULE_SOURCES+=constr_CHOICE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE.h
ASN_MODULE_SOURCES+=constr_SEQUENCE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=constr_SET_OF.h
ASN_MODULE_SOURCES+=constr_SET_OF.c
ASN_MODULE_HEADERS+=asn_application.h
ASN_MODULE_HEADERS+=asn_system.h
ASN_MODULE_HEADERS+=asn_codecs.h
ASN_MODULE_HEADERS+=asn_internal.h
ASN_MODULE_HEADERS+=OCTET_STRING.h
ASN_MODULE_SOURCES+=OCTET_STRING.c
ASN_MODULE_HEADERS+=BIT_STRING.h
ASN_MODULE_SOURCES+=BIT_STRING.c
ASN_MODULE_SOURCES+=asn_codecs_prim.c
ASN_MODULE_HEADERS+=asn_codecs_prim.h
ASN_MODULE_HEADERS+=ber_tlv_length.h
ASN_MODULE_SOURCES+=ber_tlv_length.c
ASN_MODULE_HEADERS+=ber_tlv_tag.h
ASN_MODULE_SOURCES+=ber_tlv_tag.c
ASN_MODULE_HEADERS+=ber_decoder.h
ASN_MODULE_SOURCES+=ber_decoder.c
ASN_MODULE_HEADERS+=der_encoder.h
ASN_MODULE_SOURCES+=der_encoder.c
ASN_MODULE_HEADERS+=constr_TYPE.h
ASN_MODULE_SOURCES+=constr_TYPE.c
ASN_MODULE_HEADERS+=constraints.h
ASN_MODULE_SOURCES+=constraints.c
ASN_MODULE_HEADERS+=xer_support.h
ASN_MODULE_SOURCES+=xer_support.c
ASN_MODULE_HEADERS+=xer_decoder.h
ASN_MODULE_SOURCES+=xer_decoder.c
ASN_MODULE_HEADERS+=xer_encoder.h
ASN_MODULE_SOURCES+=xer_encoder.c
ASN_MODULE_HEADERS+=per_support.h
ASN_MODULE_SOURCES+=per_support.c
ASN_MODULE_HEADERS+=per_decoder.h
ASN_MODULE_SOURCES+=per_decoder.c
ASN_MODULE_HEADERS+=per_encoder.h
ASN_MODULE_SOURCES+=per_encoder.c
ASN_MODULE_HEADERS+=per_opentype.h
ASN_MODULE_SOURCES+=per_opentype.c
ASN_CONVERTER_SOURCES+=converter-sample.c


lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
CONVERTION_TOOL = convert
TARGET = libSupl.o
TARGET_LIB = libSupl.a
#CFLAGS += -I. -g -DPDU=ULP_PDU -DEMIT_ASN_DEBUG=1
#CFLAGS += -I. -g -DPDU=ULP_PDU
CFLAGS += -I. -g -fPIC
OBJS=${ASN_MODULE_SOURCES:.c=.o} 

all: $(TARGET_LIB) 


conv: $(CONVERTION_TOOL)

$(CONVERTION_TOOL): $(TARGET_LIB)
	$(CC) $(CFLAGS) converter-sample.c $(TARGET_LIB) -o $(CONVERTION_TOOL)

$(TARGET_LIB): ${OBJS}
	$(AR) rcs $(TARGET_LIB) ${OBJS} 

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET_LIB)
	rm -f $(TARGET)
	rm -f $(OBJS)
	rm -f $(CONVERTION_TOOL)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	/home/foni/src/asn1c/asn1c/asn1c -gen-PER -fnative-types -fskeletons-copy supl.asn rrlp.asn rrlp-components.asn MAP-ExtensionDataTypes.asn MAP-LCS-DataTypes.asn

