/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-ExtensionDataTypes"
 * 	found in "MAP-ExtensionDataTypes.asn"
 * 	`asn1c -gen-PER -fnative-types`
 */

#ifndef	_PrivateExtensionList_H_
#define	_PrivateExtensionList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PrivateExtension;

/* PrivateExtensionList */
typedef struct PrivateExtensionList {
	A_SEQUENCE_OF(struct PrivateExtension) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrivateExtensionList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrivateExtensionList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PrivateExtension.h"

#endif	/* _PrivateExtensionList_H_ */
#include <asn_internal.h>
