/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-AUTH-REQ"
 * 	found in "supl.asn"
 * 	`asn1c -gen-PER -fnative-types`
 */

#ifndef	_SETNonce_H_
#define	_SETNonce_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SETNonce */
typedef BIT_STRING_t	 SETNonce_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SETNonce;
asn_struct_free_f SETNonce_free;
asn_struct_print_f SETNonce_print;
asn_constr_check_f SETNonce_constraint;
ber_type_decoder_f SETNonce_decode_ber;
der_type_encoder_f SETNonce_encode_der;
xer_type_decoder_f SETNonce_decode_xer;
xer_type_encoder_f SETNonce_encode_xer;
per_type_decoder_f SETNonce_decode_uper;
per_type_encoder_f SETNonce_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SETNonce_H_ */
#include <asn_internal.h>
