/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-AUTH-RESP"
 * 	found in "supl.asn"
 * 	`asn1c -gen-PER -fnative-types`
 */

#ifndef	_SPCAuthKey_H_
#define	_SPCAuthKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SPCAuthKey_PR {
	SPCAuthKey_PR_NOTHING,	/* No components present */
	SPCAuthKey_PR_shortKey,
	SPCAuthKey_PR_longKey,
	/* Extensions may appear below */
	
} SPCAuthKey_PR;

/* SPCAuthKey */
typedef struct SPCAuthKey {
	SPCAuthKey_PR present;
	union SPCAuthKey_u {
		BIT_STRING_t	 shortKey;
		BIT_STRING_t	 longKey;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SPCAuthKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SPCAuthKey;

#ifdef __cplusplus
}
#endif

#endif	/* _SPCAuthKey_H_ */
#include <asn_internal.h>
