/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-AUTH-RESP"
 * 	found in "supl.asn"
 * 	`asn1c -gen-PER -fnative-types`
 */

#ifndef	_SUPLAUTHRESP_H_
#define	_SUPLAUTHRESP_H_


#include <asn_application.h>

/* Including external dependencies */
#include "KeyIdentity3.h"
#include "StatusCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SPCAuthKey;

/* SUPLAUTHRESP */
typedef struct SUPLAUTHRESP {
	struct SPCAuthKey	*sPCAuthKey	/* OPTIONAL */;
	KeyIdentity3_t	*keyIdentity3	/* OPTIONAL */;
	StatusCode_t	*statusCode	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SUPLAUTHRESP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SUPLAUTHRESP;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SPCAuthKey.h"

#endif	/* _SUPLAUTHRESP_H_ */
#include <asn_internal.h>
