/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-AUTH-REQ"
 * 	found in "supl.asn"
 * 	`asn1c -gen-PER -fnative-types`
 */

#ifndef	_SUPLAUTHREQ_H_
#define	_SUPLAUTHREQ_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SETNonce.h"
#include "KeyIdentity2.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SUPLAUTHREQ */
typedef struct SUPLAUTHREQ {
	SETNonce_t	 sETNonce;
	KeyIdentity2_t	 keyIdentity2;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SUPLAUTHREQ_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SUPLAUTHREQ;

#ifdef __cplusplus
}
#endif

#endif	/* _SUPLAUTHREQ_H_ */
#include <asn_internal.h>
