ifeq ($(BOARD_WLAN_DEVICE),sc2341)
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_STRIP_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := sprdwl.ko
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/root/lib/modules
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

ifeq ($(strip $(MACH_SAMSUNG)),true)
CUSTOM := MACH_SAMSUNG
endif

ifeq ($(TARGET_BUILD_VARIANT),user)
  DEBUGMODE := BUILD=no
else
  DEBUGMODE := $(DEBUGMODE)
endif

ifeq ($(TARGET_ARCH),arm64)
ARCH_ := arm64
CROSS_COMPILE_ := aarch64-linux-android-
else
ARCH_ := arm
CROSS_COMPILE_ := arm-eabi-
endif

$(LOCAL_PATH)/sprdwl.ko: $(TARGET_PREBUILT_KERNEL)
	$(MAKE) -C $(shell dirname $@) ARCH=$(ARCH_) CROSS_COMPILE=$(CROSS_COMPILE_) SPRDWL_PLATFORM=$(TARGET_BOARD_PLATFORM) USING_PP_CORE=$(TARGET_GPU_PP_CORE) DFS_MAX_FREQ=$(TARGET_GPU_DFS_MAX_FREQ) DFS_MIN_FREQ=$(TARGET_GPU_DFS_MIN_FREQ) $(DEBUGMODE) KDIR=$(ANDROID_PRODUCT_OUT)/obj/KERNEL clean
	$(MAKE) -C $(shell dirname $@) ARCH=$(ARCH_) CROSS_COMPILE=$(CROSS_COMPILE_) SPRDWL_PLATFORM=$(TARGET_BOARD_PLATFORM) USING_PP_CORE=$(TARGET_GPU_PP_CORE) DFS_MAX_FREQ=$(TARGET_GPU_DFS_MAX_FREQ) DFS_MIN_FREQ=$(TARGET_GPU_DFS_MIN_FREQ) $(DEBUGMODE) KDIR=$(ANDROID_PRODUCT_OUT)/obj/KERNEL CUSTOM_EXTRA=$(CUSTOM)
endif
