# Spreadtrum Communications Inc.
# Remove macro
# ifneq ($(strip $(PDK_FUSION_PLATFORM_ZIP)),)
LOCAL_PATH := $(call my-dir)

# prebild of priv-app ----------

# CalendarProvider
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := CalendarProvider
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Contacts
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Contacts
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# ContactsProvider
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := ContactsProvider
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# ExternalStorageProvider
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := ExternalStorageProvider
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# ExternalStorageProvider
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Launcher2
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Dialer
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Dialer
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Mms
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Mms
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# MusicFX
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := MusicFX
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# TeleService
#include $(CLEAR_VARS)
#LOCAL_MODULE_TAGS := optional
#LOCAL_PREBUILD_NAME := TeleService
#LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
#LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
#LOCAL_MODULE_CLASS := APPS
#LOCAL_CERTIFICATE := PRESIGNED
#LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
#LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
#LOCAL_PREBUILD_NAME :=
#include $(BUILD_PREBUILT)

# Telecom
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Telecom
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# MmsService
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := MmsService
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# FdnService
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := FdnService
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_SRC_FILES := priv-app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# prebuild of app ----------------------

# Calculator
#include $(CLEAR_VARS)
#LOCAL_MODULE_TAGS := optional
#LOCAL_PREBUILD_NAME := KeyChain
#LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
#LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
#LOCAL_MODULE_CLASS := APPS
#LOCAL_CERTIFICATE := PRESIGNED
#LOCAL_MODULE_PATH := $(TARGET_OUT)/app
#LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
#LOCAL_PREBUILD_NAME :=
#include $(BUILD_PREBUILT)

# Calculator
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Calculator
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# DeskClock
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := DeskClock
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Calendar
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Calendar
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Email
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Email
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Exchange2
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Exchange2
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Gallery2
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Gallery2
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=

LOCAL_PREBUILT_JNI_LIBS := \
    lib/arm/libjni_eglfence.so \
    lib/arm/libjni_jpegstream.so \
    lib/arm/libjni_filtershow_filters.so \
    lib/arm/librsjni.so

#LOCAL_REQUIRED_MODULES := \
#    libjni_eglfence \
#    libjni_filtershow_filters \
#    libjni_jpegstream

include $(BUILD_PREBUILT)

# Launcher3
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Launcher3
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Music
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Music
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# Gmail
#include $(CLEAR_VARS)
#LOCAL_MODULE_TAGS := optional
#LOCAL_PREBUILD_NAME := Gmail
#LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
#LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
#LOCAL_MODULE_CLASS := APPS
#LOCAL_CERTIFICATE := PRESIGNED
#LOCAL_MODULE_PATH := $(TARGET_OUT)/app
#LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
#LOCAL_PREBUILD_NAME :=
#include $(BUILD_PREBUILT)

# Browser Chrome
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := Chrome
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
LOCAL_REQUIRED_MODULES := \
    libchrome.2125.102.so \
    libchromium_android_linker.so

include $(BUILD_PREBUILT)

# SoundRecorder
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := SoundRecorder
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# FileExplorer
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := FileExplorer
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_OVERRIDE_PACKAGES := $(LOCAL_PREBUILD_NAME)
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# EngineerMode
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := EngineerMode
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_OVERRIDE_PACKAGES := $(LOCAL_PREBUILD_NAME)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

# DocumentsUI
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILD_NAME := DocumentsUI
LOCAL_MODULE_STEM := $(LOCAL_PREBUILD_NAME).apk
LOCAL_MODULE := Prebuild$(LOCAL_PREBUILD_NAME)
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := app/$(LOCAL_MODULE_STEM)
LOCAL_PREBUILD_NAME :=
include $(BUILD_PREBUILT)

######  --- lib
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libchromium_android_linker.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := lib/libchromium_android_linker.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libchrome.2125.102.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := lib/libchrome.2125.102.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Prebuildbootanimation
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_STEM := bootanimation.zip
LOCAL_MODULE_PATH := $(TARGET_OUT)/media
LOCAL_SRC_FILES := etc/bootanimation.zip
include $(BUILD_PREBUILT)

include $(call all-makefiles-under, $(LOCAL_PATH))
# endif
