
package com.android.sprd.telephony;

public interface RIConstants {

    int MISSING_RESOURCE = 29;
    int NO_SUCH_ELEMENT = 30;

    String RADIOINTERACTOR_SERVER = "irit";

    int RI_REQUEST_RADIOINTERACTOR = -1;
    int RI_REQUEST_OEM_HOOK_STRINGS = 60;
    int RI_REQUEST_SIM_TRANSMIT_APDU_BASIC = 114;
    int RI_REQUEST_SIM_OPEN_CHANNEL = 115;
    int RI_REQUEST_SIM_CLOSE_CHANNEL = 116;
    int RI_REQUEST_SIM_TRANSMIT_APDU_CHANNEL = 117;
    int RI_REQUEST_GET_SIM_CAPACITY = 5042;
    int RI_REQUEST_GET_HD_VOICE_STATE = 5501;
    int RI_REQUEST_SIM_GET_ATR = 5502;
    int RI_REQUEST_SIM_OPEN_CHANNEL_WITH_P2 = 5503;
    int RI_REQUEST_ENABLE_RAU_NOTIFY = 5504;
    int RI_REQUEST_ENABLE_COLP = 5505;
    int RI_REQUEST_STORE_SMS_TO_SIM = 5506;
    int RI_REQUEST_QUERY_SMS_STORAGE_MODE = 5507;

    int RI_UNSOL_RI_CONNECTED = 6500;
    int RI_UNSOL_RADIOINTERACTOR_EMBMS = 6501;
}
