LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := busybox
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
ifeq ($(TARGET_BUILD_VARIANT),user)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := busybox_tiny
else
LOCAL_MODULE_TAGS := debug
LOCAL_SRC_FILES := busybox
endif
include $(BUILD_PREBUILT)


