make  SCONS_CONFIGS="CONFIG_MALI_MIDGARD=m CONFIG_MALI_DEBUG=y CONFIG_MALI_PLATFORM_THIRDPARTY=y CONFIG_MALI_PLATFORM_THIRDPARTY_NAME=sc9838 CONFIG_MALI_MIDGARD_DVFS=y MALI_INSTRUMENTATION_LEVEL=0 CONFIG_MALI_GATOR_SUPPORT=n" $1
rm .*.cmd *.o
