#ifndef __STRING_EN_H__
#define __STRING_EN_H__

#define MENU_TITLE_ROOT		"* Spreadtrum Factory Test "
#define MENU_CHANGE_LANGUAGE		"< Change the Displaying Language"
#define MENU_TITLE_PHONETEST	"* Phone Test Item "
#define MENU_TITLE_VERSION      "* Software Version 0.1 "
#define MENU_TITLE_BREAKLINE	"*****************************"
#define MENU_TITLE_VERSION		"=== Phone Software Version ==="
#define MENU_BACK               "< Go Back"
#define MENU_BOARD_AUTOTEST   	"> Board Auto Test"
#define MENU_BOARD_SINGLETEST  	"> Board Single Test Item"
#define MENU_PHONE_AUTOTEST		"> Phone Auto Test"
#define MENU_PHONE_SINGLETEST	"> Phone Single Test Item"
#define MENU_NOT_AUTO_TEST		"> Proposed Items"
#define MENU_PHONE_INFO		"> Phone Information"
#define MENU_BOARD_REPORT		"> Board Test Report"
#define MENU_PHONE_REPORT		"> Phone Test Report"
#define MENU_NOT_AUTO_REPORT		"> Proposed Test Report"
#define MENU_PHONE_REBOOT		"< Reboot"
#define MENU_FACTORY_RESET		"< Factory Reset"
#define MENU_CALI_INFO		"> Cali Info"
#define MENU_VERSION		"> Version"
#define MENU_PHONE_INFO_TEST		"> Phone Info Test"
#define MENU_TEST_KEY		"> Test Key"
#define MENU_TEST_LCD		"> Test Lcd"
#define MENU_TEST_VIBRATOR		"> Test Vibrator"
#define MENU_TEST_BACKLIGHT		"> Test Backlight"
#define MENU_TEST_VB_BL		"> Test Vibrator & Backlight"
#define MENU_TEST_LED		"> Test LED"
#define MENU_TEST_TP		"> Test TP"
#define MENU_TEST_MULTI_TOUCH		"> Test Multi TP"
#define MENU_TEST_PHONE_LOOPBACK		"> Test Phone Loopback"
#define MENU_TEST_SDCARD		"> Test Sdcard"
#define MENU_TEST_EMMC		"> Test EMMC"
#define MENU_TEST_RTC		"> Test RTC"
#define MENU_TEST_MAINLOOP		"> Test Main Loopback"
#define MENU_TEST_ASSISLOOP		"> Test Assis Loopback"
#define MENU_TEST_SENSOR		"> Test Sensor"
#define MENU_TEST_ASENSOR		"> Test Accelerometer"
#define MENU_TEST_GSENSOR		"> Test Gyroscope"
#define MENU_TEST_MSENSOR		"> Test Magnetic"
#define MENU_TEST_PSENSOR		"> Test Pressure"
#define MENU_TEST_LSENSOR		"> Test Light&Proximity"
#define MENU_TEST_FCAMERA		"> Test Front Camera"
#define MENU_TEST_FACAMERA		"> Test Front Aux Camera"
#define MENU_TEST_BCAMERA_FLASH		"> Test Back Camera"
#define MENU_TEST_ACAMERA		"> Test Back Aux Camera"
#define MENU_TEST_BCAMERA		"> Test Back Camera"
#define MENU_TEST_FLASH		"> Test Flash"
#define MENU_TEST_CHARGE		"> Test Charge"
#define MENU_TEST_HEADSET		"> Test Headset"
#define MENU_TEST_FM		"> Test FM"
#define MENU_TEST_BT		"> Test Bluetooth"
#define MENU_TEST_WIFI		"> Test WiFi"
#define MENU_TEST_GPS		"> Test GPS"
#define MENU_TEST_TEL		"> Test Tel"
#define MENU_TEST_OTG		"> Test OTG"
#define MENU_TEST_SIMCARD		"> Test SIM Card"
#define MENU_TEST_RECEIVER		"> Test Receiver"
#define MENU_TEST_SPEAKER		"> Test Speaker"
#define MENU_CALI_ACCSOR		"> Acceler Cali"
#define MENU_CALI_CYRSOR                       "> Gyroscope Cali"
#define MENU_CALI_MAGSOR		"> Magnetic Cali"
#define MENU_CALI_PROSOR		"> Proximity Manual Cali"
#define MENU_CALI_AUTOPROSOR		"> Proximity Auto Cali"
#define MENU_TEST_SOUNDTRIGGER		"> Test Soundtrigger"
#define MENU_TEST_FINGERSOR		"> Test Fingersor"
#define FINGER_DLOPEN_FAIL		"Fingersor Lib Open Failed!"
#define TEXT_TEST_FAIL_CASE		"Retest Fail"
#define MENU_MULTI_TEST		"> Multi Test Report"
#define TEXT_IMEI               		"IMEI:"
#define TEXT_SN                 		"SN:"
#define TEXT_INVALIDSN1         		"Invalid sn1"
#define TEXT_INVALIDSN2         		"Invalid sn2"
#define TEXT_INVALID_WIFI         		"Invalid WIFI Mac"
#define TEXT_BT_ADDR				    "Bluetooth Mac:"
#define TEXT_PHASE_CHECK_RESULT 		"Phasecheck Result:"
#define TEXT_INVALID            		"Invalid"
#define TEXT_VALID              		"Valid"
#define TEXT_GETFAIL		"get failed"
#define TEXT_PHASE_PASS         		"PASS"
#define TEXT_PHASE_FAILED       		"FAILED"
#define TEXT_PHASE_NOTTEST      		"NOT TEST"
#define TEXT_WIFI_ADDR		 "WIFI Mac:"
#define TEXT_PRE_PAGE		"Pre"
#define TEXT_NEXT_PAGE		"Next"
#define TEXT_PASS		"PASS"
#define TEXT_FAIL		"FAIL"
#define TEXT_GOBACK		"Back"
#define TEXT_START		"Start"
#define TEXT_NA		"NA"
#define TEXT_NS		"NS"
#define TEXT_TEST_PASS		"Test Pass!"
#define TEXT_TEST_FAIL		"Test Fail!"
#define TEXT_TEST_TIMEOUT		"Test Timeout!"
#define TEXT_ANY_KEY		"Press Anykey to Continue"
#define TEXT_FINISH		"Test Finish!!"
#define TEXT_OPEN_DEV_FAIL		"Open Device Failed!"
#define TEXT_WAIT_TIPS		"Wait Please..."
#define LCD_TEST_TIPS		"White/black/red/green/blue on Screen!"
#define TEXT_VIB_START		"Start Shaking"
#define TEXT_VIB_FINISH		"Stop Shaking"
#define TEXT_BL_ILLUSTRATE		"The Backlight is Changing!"
#define TEXT_MULTI_TOUCH_START		"Narrow the Colors, Please!"
#define TEXT_BL_OVER		"Backligth Changing is Over!"
#define TEXT_LED_TIPS		"The LED is Flickering!"
#define TEXT_LED_RED		"The Red LED is Blinking"
#define TEXT_LED_GREEN		"The Green LED is Blinking"
#define TEXT_LED_BLUE		"The Blue LED is Blinking"
#define TEST_LED_NOTSUPPORT		"There is No LED!"
#define TEXT_KEY_ILLUSTRATE		"Please Press the Keys!"
#define TEXT_KEY_VOLUMEDOWN		"Volumedown Key"
#define TEXT_KEY_VOLUMEUP		"Volumeup Key"
#define TEXT_KEY_POWER		"Power Key"
#define TEXT_KEY_MENU		"Menu Key"
#define TEXT_KEY_BACK		"Back Key"
#define TEXT_KEY_HOMEPAGE		"Homepage Key"
#define TEXT_KEY_CAMERA		"Camera Key"
#define TEST_ASSIS_NOTSUPPORT		"There is No Assis Mic!"
#define TEXT_LB_MICSPEAKER		"Please Test the Mic&Speaker Loop..."
#define TEXT_LB_MICRECEIVER		"Please Test the Mic&Receiver Loop..."
#define TEXT_RECV_PLAYING		"Audio is Playing on the Receiver..."
#define TEXT_SPE_PLAYING		"Audio is Playing on the Speaker..."
#define TEXT_CHG_BATTER_VOL		"The Voltage of the Battery"
#define TEXT_CHG_RUN_Y		"In Charging..."
#define TEXT_CHG_RUN_N		"Not in Charging!"
#define TEXT_CHG_TYPE		"Charging Type:"
#define TEXT_CHG_VOL		"Charging Voltage:"
#define TEXT_CHG_CUR		"Charging Current:"
#define TEXT_BATTARY_CUR		"Battery Charging Current:"
#define TEXT_SD_START		"Start Testing SD:"
#define TEXT_SD_OPEN_OK		 "SD Open Success!"
#define TEXT_SD_STATE_OK		"SD Capacity:"
#define TEXT_SD_STATE_FAIL		"Failed to Get SD Capacity!"
#define TEXT_SD_RW_OK		"SD RW Testing Good!"
#define TEXT_SD_OPEN_FAIL			"SD Open Failed!"
#define TEXT_SD_RW_FAIL		"SD RW Failed!"
#define TEXT_EMMC_STATE		"The State of EMMC:"
#define TEXT_EMMC_CAPACITY		"The Capacity of EMMC:"
#define TEXT_EMMC_OK		"EMMC on the Phone"
#define TEXT_EMMC_FAIL		"No EMMC on the Phone"
#define TEXT_SIM1		"Test SIM1"
#define TEXT_SIM2		"Test SIM2"
#define TEXT_SIM_SCANING		"SIM is Testing..."
#define TEXT_SIM_RESULT		"SIM Testing Result:"
#define TEXT_MODEM_INITING		"SIM is Opening, Please Wait!"
#define TEXT_RTC_TIME		"RTC Time"
#define TEXT_HD_UNINSERT		"Headset Uninsert!"
#define TEXT_HD_INSERTED		"Headset Inserted!"
#define TEXT_HD_HAS_MIC		"Mic on Headset"
#define TEXT_HD_NO_MIC		"No Mic on Headset"
#define TEXT_HD_MICHD		"Please Test the HD&Speaker Loop..."
#define TEXT_HD_KEY_STATE		"Key State on Headset:"
#define TEXT_HD_KEY_PRESSED		"Pressed!"
#define TEXT_HD_KEY_RELEASE		"Release!"
#define TEXT_FM_SEEK_TIMEOUT		"Seeking Timeout!"
#define TEXT_FM_FAIL		"FM Testing Failed!"
#define TEXT_FM_OK		"FM Testing Success!"
#define TEXT_FM_FREQ		"Searching Freq"
#define TEXT_FM_STRE		"Signal Intensity"
#define TEXT_FM_SCANING		"FM Scaning..."
#define TEXT_FM_SET_SUCCESS		"FM Setting Success"
#define TEXT_FM_SET_FAIL		"FM Setting Failed"
#define TEXT_SENSOR_OPEN_FAIL		"Open Sensor Failed!!"
#define TEXT_SENSOR_OPEN_OK		"Open Sensor Success!!"
#define TEXT_SENSOR_DEV_INFO		"The Info of the Sensor:"
#define TEXT_SENSOR_PASS		"Pass!"
#define TEXT_AS_OPER1		"Accelerometer Sensor Testing..."
#define TEXT_AS_OPER2		"Please Put the Phone in X/Y/Z!"
#define TEXT_GS_OPER1		"Gyroscope Sensor Testing..."
#define TEXT_GS_OPER2		"Please Shaking the Phone!"
#define TEXT_GS_X		"X-axis:"
#define TEXT_GS_Y		"Y-axis:"
#define TEXT_GS_Z		"Z-axis:"
#define TEXT_ACC_OPER		"Light Distance Sensor Testing..."
#define TEXT_PRS_OPER1		"Pressure Sensor Testing..."
#define TEXT_PrS_Value		"Pressure Sensor Value:"
#define TEXT_PS_NEAR				"Proximity Sensor Near"
#define TEXT_PS_FAR				"Proximity Sensor Far"
#define TEXT_LS_LUX				"Light Sensor Lux: "
#define TEXT_MS_X                   		"Azimuth:"
#define TEXT_MS_Y                   		"Pitch:"
#define TEXT_MS_Z                   		"Roll:"
#define TEXT_MS_OPER1		"Magnetic Sensor Testing..."
#define TEXT_MS_OPER2		"Please Shaking the Phone!"
#define CAMERA_START		"Watch the Image on the Phone"
#define CAMERA_LIGHT_ON		"The Flash is On"
#define CHARGE_TIPS		"Battery is Full!"
#define TEXT_BT_SCANING		"BT Scaning..."
#define TEXT_BT_MAC		"BT MAC:"
#define TEXT_UID		"UID:"
#define BT_BACK_TEST		"BT is Testing, Please Wait!"
#define TEXT_WIFI_SCAN		"WiFi Scaning Result:"
#define OTG_TEST_START		"OTG Testing Start:"
#define OTG_NOT_SUPPORT		"Does Not Support OTG!"
#define OTG_SUPPORT		"OTG support"
#define OTG_INSERT		"OTG Inserted!"
#define OTG_UNSERT		"OTG Uninsert!"
#define OTG_DEVICE		"OTG Device!"
#define OTG_HOST		"OTG Host!"
#define OTG_DEVICE_INSERT		"Please Insert OTG in 30s!"
#define TEXT_OTG_CAPACITY		"OTG Capacity:"
#define TEXT_OTG_UDISK_OK		"OTG Udisk Test Ok!"
#define TEXT_OTG_UDISK_NO		"Does Not Test the Udisk!"
#define TEXT_OTG_UDISK_SCANING		"OTG Udisk Scaning..."
#define TEL_TEST_START		"Call in 112..."
#define TEL_TEST_TIPS		"Please Pay Attention to the Voice!"
#define TEL_DIAL_OVER		"Be Calling..."
#define TEL_DIAL_FAIL		"Open Stack Failed, Please Wait!"
#define TEXT_TEST_NA				"Test Unfinish!"
#define TEXT_HD_REINSERT		"Please Reinsert the Headset!"
#define AS_CALI_OPER1				"Put Phone on the Level, Acceler Caling..."
#define GS_CALI_OPER1				"Put Phone on the Level, Gyroscope Caling..."
#define MAG_CALI_OPER1				"Reading Magnetic Cali data..."
#define MAG_CALI_OPER2				"Please Import Cali Data or Recali again!"
#define PRO_CALI_OPER1				"Put Phone on the Level without shelter"
#define PRO_CALI_OPER2				"Put Shelter 3cm away from the Sensor， and Press Start Button"
#define PRO_CALI_OPER3				"Put Shelter 5cm away from the Sensor， and Press Start Button"
#define TEXT_CALI_PASS				"Sensor Cali Success！"
#define TEXT_CALI_FAIL				"Sensor Cali Failed！"
#define TEXT_CALI_NA				"Sensor Cali Unfinish！"
#define TEXT_SENSOR_OPEN			"Sensor is Opening, Please Wait..."
#define TEXT_SENSOR_CALI			"Sensor on Cali, Please Wait..."
#define TEXT_SOUNDTRIGGER_OPER			"Soundtrigger being Initializing..."
#define TEXT_SOUNDTRIGGER_OPER1			"Initialization Complete, Press \"Start\" to Start Recognition..."
#define TEXT_SOUNDTRIGGER_OPER2			"Initialization Failed! Please Try Again!"
#define TEXT_SOUNDTRIGGER_OPER3			"Recognition Timeout!"
#define TEXT_SOUNDTRIGGER_OPER4			"Recognition Starting..."
#define FINGER_INIT                 "Fingersor Being Initialized, Please Do Not Touch The FingerSor!"
#define FINGER_SENSOR_BAD			"FingerSor Recognition Failed!"
#define TEXT_FINGERSOR_OPER1			"Put Finger on Fingersor, Press \"Start\" to Start Recognition..."
#define TEXT_FINGERSOR_OPER			"Please Do Not Touch The Fingersor，Press \"Start\" to Init"

#define TEXT_CAPTURE            "capture"
#endif /*STRING_EN_H*/
